### PR TITLE
FRW-286 Stabilized Glue infrastructure

### PR DESCRIPTION
**Pull request by yaroslav-spryker**
- Developer(s): @yaroslav-spryker 

- Ticket: https://spryker.atlassian.net/browse/FRW-286

- Release Group: https://release.spryker.com/release-groups/view/4390

- merge: squash

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   UnzerRestApi             | patch (currently 0.x)                 |                     |

-----------------------------------------

##### Change log

Adjustments

- Adjusted composer.json to allow for new `GlueJsonApiConventionExtension` major.

### CODE REVIEW

**Review by asmarovydlo — APPROVED** [review]

**Comment by asmarovydlo** [comment]
Can be released with the red Travis, same issue in the master.
No code changes in the PR. (Target extension module was stabilized without changing functionality)

**Comment by limeeugenia** [comment]
Please check the change logs, they are not relevant to the change made.

**Comment by asmarovydlo** [comment]
> Please check the change logs, they are not relevant to the change made.

Could you please clarify what is wrong with the changelogs? @limeeugenia 
We've allowed a new major according to https://spryker.atlassian.net/wiki/spaces/CORE/pages/523730976/Release+Notes+and+Changelogs

**Comment by yaroslav-spryker** [comment]
> > Please check the change logs, they are not relevant to the change made.
> 
> Could you please clarify what is wrong with the changelogs? @limeeugenia We've allowed a new major according to https://spryker.atlassian.net/wiki/spaces/CORE/pages/523730976/Release+Notes+and+Changelogs

I have already fixed the wrong module name in the change log, I think this was the issue.

**Pull request merged**
